"""add unique constraint to reminders maintenance_id reminder_type

Revision ID: 15095bce4267
Revises: db03dd3be3fd
Create Date: 2026-09-15 08:13:37.464022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15095bce4267'
down_revision: Union[str, None] = 'db03dd3be3fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_reminders_maintenance_type', 'reminders', ['maintenance_id', 'reminder_type'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_reminders_maintenance_type', 'reminders', type_='unique')
    # ### end Alembic commands ###
