"""
Response schema for Reminders (SRS §3.7 FR-REM-01; Data Dictionary
`reminders` table; System Specification §11 `/reminders` GET, §15, §27
Phase 10).

No client-writable create schema: reminders are generated only by
reminder_service.generate_due_reminders_for_user (System Specification §15:
"Reminders are generated by a backend scheduler process"), and the API
table (§11) lists only `GET /reminders` — the same "server-triggered only"
pattern already used for notifications (see app/schemas/notification.py).
"""

import uuid
from datetime import date, datetime

from pydantic import BaseModel, ConfigDict


class ReminderRead(BaseModel):
    model_config = ConfigDict(from_attributes=True)

    id: uuid.UUID
    drone_id: uuid.UUID
    maintenance_id: uuid.UUID | None
    reminder_type: str
    due_date: date
    status: str
    created_at: datetime


class ReminderListResponse(BaseModel):
    items: list[ReminderRead]
    total: int
